name: auto trigger workflows

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["delete old workflows"]
    types:
      - completed

jobs:
  build:
    name: build r66s ${{matrix.source}}
    strategy:
      fail-fast: false
      matrix:
        source: [immortalwrt, lede]

    uses: ./.github/workflows/build-r66s-openwrt.yml
    with:
      source: ${{matrix.source}}
      ip_address: 10.0.0.1
      toolchain: true
      artifact: false
      release: true
